=== koenh1/pigml/schemas/wkb-entity-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2014 rel. 2 sp1 (x64) (http://www.altova.com) by Koen Hendrickx (Wolters Kluwer Belgium S.A.) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:es="http://www.wolterskluwer.com/schemas/appollo/entity/v1.0" targetNamespace="http://www.wolterskluwer.com/schemas/appollo/entity/v1.0" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="entity-schema">
		<xs:annotation>
			<xs:documentation>An entity schema</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="imports" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="module" type="es:module" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="data-types" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="data-type" type="es:data-type" minOccurs="1" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="entities" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="entity-type" type="es:entity-type" minOccurs="1" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
					<xs:unique name="state-machine-names">
						<xs:selector xpath=".//es:state-machine"/>
						<xs:field xpath="@name"/>
					</xs:unique>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="namespace" type="xs:anyURI" use="required"/>
			<xs:attribute name="at" type="xs:anyURI" use="required"/>
		</xs:complexType>
		<xs:unique name="entity-names">
			<xs:selector xpath=".//es:entity-type"/>
			<xs:field xpath="@name"/>
		</xs:unique>
		<xs:key name="type-names">
			<xs:selector xpath=".//es:data-type"/>
			<xs:field xpath="@name"/>
		</xs:key>
		<xs:key name="module-names">
			<xs:selector xpath="es:imports/es:module"/>
			<xs:field xpath="@name"/>
		</xs:key>
		<xs:keyref name="module-ref" refer="es:module-names">
			<xs:selector xpath=".//es:action"/>
			<xs:field xpath="@module"/>
		</xs:keyref>
		<xs:keyref name="type-ref" refer="es:type-names">
			<xs:selector xpath=".//es:action"/>
			<xs:field xpath="@argument-type"/>
		</xs:keyref>
		<xs:keyref name="action-ref" refer="es:action-names">
			<xs:selector xpath=".//es:event"/>
			<xs:field xpath="@action"/>
		</xs:keyref>
		<xs:unique name="unique-state-names">
			<xs:selector xpath=".//es:state"/>
			<xs:field xpath="@name"/>
		</xs:unique>
		<xs:keyref name="guard-state-ref" refer="es:state-names">
			<xs:selector xpath=".//es:guard"/>
			<xs:field xpath="@state"/>
		</xs:keyref>
		<xs:key name="action-names">
			<xs:selector xpath=".//es:action|.//es:constructor"/>
			<xs:field xpath="@name"/>
		</xs:key>
	</xs:element>
	<xs:complexType name="entity-type">
		<xs:sequence>
			<xs:element name="constructors" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="constructor" type="es:namedaction" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="canonizer" type="es:canonaction" minOccurs="1" maxOccurs="1"/>
			<xs:element name="actions" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="action" type="es:namedaction" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="state-machine" type="es:state-machine" minOccurs="0" maxOccurs="unbounded">
				<xs:key name="state-names">
					<xs:selector xpath=".//es:state"/>
					<xs:field xpath="@name"/>
				</xs:key>
				<xs:keyref name="state-ref" refer="es:state-names">
					<xs:selector xpath=".//es:target"/>
					<xs:field xpath="@state"/>
				</xs:keyref>
				<xs:keyref name="inital-state-ref" refer="es:state-names">
					<xs:selector xpath="."/>
					<xs:field xpath="@initial-state"/>
				</xs:keyref>
				<xs:keyref name="error-state-ref" refer="es:state-names">
					<xs:selector xpath="."/>
					<xs:field xpath="@error-state"/>
				</xs:keyref>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="version" use="required" type="es:version"/>
		<xs:attribute name="name" type="xs:Name" use="required"/>
		<xs:attribute name="directory" type="xs:anyURI" use="required"/>
		<xs:attribute name="depth" default="1">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="1"/>
					<xs:enumeration value="unbounded"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="state-machine">
		<xs:annotation>
			<xs:documentation>In each state machine exactly one state is active at the time. 
			The idea is that different state machine describes orthogonal aspects of the entity state.
			It should be possible to refactor any workflow into this form.  
		</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element ref="es:state" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:Name" use="required"/>
		<xs:attribute name="initial-state" use="required"/>
		<xs:attribute name="error-state" use="required"/>
	</xs:complexType>
	<xs:element name="state">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="es:event" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:Name" use="required"/>
			<xs:attribute name="initial" type="xs:boolean" use="optional" fixed="true"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="event">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="guard" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>A guard allows one to specify that a different state machine must be in some specific state or states. If multiple guard states are specified from a single state machine, the conditions are OR-ed. Guard referring to different state machines are AND-ed.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="state" use="required"/>
						<xs:attribute name="invert" type="xs:boolean" default="false"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="target" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>If multiple output states are specified, the action should return exactly one of these state names, otherwise a run-time-error is generated (and the transaction is aborted).</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="state" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="action" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="data-type">
		<xs:choice minOccurs="0">
			<xs:element name="schema" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="schema-location" use="required"/>
					<xs:attribute name="namespace" use="required"/>
					<xs:attribute name="element" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="any-xml" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="namespace" use="optional"/>
					<xs:attribute name="element" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:choice>
		<xs:attribute name="type" type="xs:QName" use="optional"/>
		<xs:attribute name="name" type="xs:Name" use="required"/>
		<xs:attribute name="mime-type" use="required"/>
	</xs:complexType>
	<xs:complexType name="module">
		<xs:attribute name="name" type="xs:Name" use="required"/>
		<xs:attribute name="namespace" use="required"/>
		<xs:attribute name="at" use="required"/>
	</xs:complexType>
	<xs:complexType name="action">
	<xs:sequence minOccurs="0" maxOccurs="unbounded">
		<xs:choice>
		<xs:element name="match-execute-privilege" type="es:security-assert"/>
		<xs:element name="match-security-role" type="es:security-assert"/>
		</xs:choice>
	</xs:sequence>
		<xs:attribute name="function" use="required"/>
		<xs:attribute name="module" use="optional"/>
		<xs:attribute name="argument-type" use="optional"/>
		<xs:attribute name="async" type="xs:boolean" default="false"/>
	</xs:complexType>
	<xs:complexType name="namedaction">
		<xs:complexContent>
			<xs:extension base="es:action">
				<xs:attribute name="name" type="xs:Name" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="canonaction">
		<xs:complexContent>
			<xs:restriction base="es:action">
				<xs:attribute name="argument-type" use="prohibited"/>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="security-assert">
	<xs:attribute name="any-of" use="required" type="xs:string"/>
	</xs:complexType>
	<xs:simpleType name="version">
		<xs:restriction base="xs:string"><xs:pattern value="\d+.\d+.\d+"/></xs:restriction>
	</xs:simpleType>
</xs:schema>

=== koenh1/pigml/data/entity-schemas/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2014 rel. 2 sp1 (x64) (http://www.altova.com)-->
<entity-schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns="http://www.wolterskluwer.com/schemas/appollo/entity/v1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.wolterskluwer.com/schemas/appollo/entity/v1.0 wkb-entity-schema.xsd" namespace="http://www.wolterskluwer.com/ns/appollo/wkbe/example" at="/generated/entities/">
	<imports>
		<module name="example" namespace="http://www.wolterskluwer.com/ns/appollo/marklogic/entity/example" at="/lib/example.xqy"/>
	</imports>
	<data-types>
		<data-type name="address" mime-type="application/x-address+xml">
			<any-xml element="address"/>
		</data-type>
		<data-type name="message" mime-type="application/x-message+xml">
			<any-xml element="message"/>
		</data-type>
		<data-type name="text" mime-type="text/plain" type="xs:string">
		</data-type>
	</data-types>
	<entities>
		<entity-type name="message" directory="/messages/" depth="1" version="1.0.0">
			<constructors>
				<constructor name="create" function="create-message" module="example" argument-type="address"/>
				<constructor name="create-from-subject" function="create-message-from-subject" module="example" argument-type="text"/>
			</constructors>
			<canonizer function="canonical" module="example"/>
			<actions>
				<action name="add-receiver" function="add-receiver" module="example" argument-type="address"/>
				<action name="add-message" function="add-message" module="example" argument-type="message"/>
				<action name="set-subject" function="set-subject" module="example" argument-type="text"/>
				<action name="send" function="send" module="example">
					<match-execute-privilege any-of="http://www.wolterskluwer.com/ns/appollo/marklogic/entity/example/permission-send"/>
					<match-security-role any-of="example-sender"/>
					<match-security-role any-of="example-sender2"/>
				</action>
			</actions>
			<state-machine name="sent-state" initial-state="unsent" error-state="draft">
				<state name="unsent">
					<event action="send" async="true">
						<guard state="ready"/>
						<target state="sent"/>
					</event>
				</state>
				<state name="sent"></state>
			</state-machine>
			<state-machine name="message-state" initial-state="incomplete" error-state="incomplete">
				<state name="incomplete">
					<event action="add-receiver">
						<guard invert="true" state="sent"/>
						<target state="ready"/>
						<target state="incomplete"/>
					</event>
					<event action="set-subject">
						<guard invert="true" state="sent"/>
						<target state="ready"/>
						<target state="incomplete"/>
					</event>
					<event action="add-message">
						<guard invert="true" state="sent"/>
						<target state="ready"/>
						<target state="incomplete"/>
					</event>
				</state>
				<state name="ready">
					<event action="add-receiver">
						<guard invert="true" state="sent"/>
						<target state="ready"/>
					</event>
					<event action="set-subject">
						<guard invert="true" state="sent"/>
						<target state="ready"/>
					</event>
					<event action="add-message">
						<guard invert="true" state="sent"/>
						<target state="ready"/>
					</event>
				</state>
				<state name="final">
				</state>
			</state-machine>
		</entity-type>
	</entities>
</entity-schema>
