=== koenh1/pigml/schemas/wkbe-workflows-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- W3C Schema generated by XMLSpy v2014 rel. 2 sp1 (x64) (http://www.altova.com) -->
<xs:schema xmlns:s="http://www.wolterskluwer.com/schemas/appollo/entity/v1.1" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.wolterskluwer.com/schemas/appollo/entity/v1.1">
	<xs:element name="event">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="s:guard" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="s:target" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="action" type="xs:Name" use="required"/>
			<xs:attribute name="argument-type" use="optional">
				<xs:simpleType>
					<xs:union>
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:pattern value="element(.+)"/>
							</xs:restriction>
						</xs:simpleType>
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="document-node()"/>
								<xs:enumeration value="node()"/>
								<xs:enumeration value="int"/>
								<xs:enumeration value="anyURI"/>
								<xs:enumeration value="base64Binary"/>
								<xs:enumeration value="boolean"/>
								<xs:enumeration value="byte"/>
								<xs:enumeration value="date"/>
								<xs:enumeration value="dateTime"/>
								<xs:enumeration value="dayTimeDuration"/>
								<xs:enumeration value="decimal"/>
								<xs:enumeration value="double"/>
								<xs:enumeration value="duration"/>
								<xs:enumeration value="float"/>
								<xs:enumeration value="gDay"/>
								<xs:enumeration value="gMonth"/>
								<xs:enumeration value="gMonthDay"/>
								<xs:enumeration value="gYear"/>
								<xs:enumeration value="gYearMonth"/>
								<xs:enumeration value="hexBinary"/>
								<xs:enumeration value="int"/>
								<xs:enumeration value="integer"/>
								<xs:enumeration value="long"/>
								<xs:enumeration value="negativeInteger"/>
								<xs:enumeration value="nonNegativeInteger"/>
								<xs:enumeration value="positiveInteger"/>
								<xs:enumeration value="nonPositiveInteger"/>
								<xs:enumeration value="short"/>
								<xs:enumeration value="string"/>
								<xs:enumeration value="time"/>
								<xs:enumeration value="unsignedByte"/>
								<xs:enumeration value="unsignedInt"/>
								<xs:enumeration value="unsignedLong"/>
								<xs:enumeration value="unsignedShort"/>
								<xs:enumeration value="yearMonthDuration"/>
								<xs:enumeration value="iri"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:union>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="guard">
		<xs:complexType>
			<xs:attribute name="state" type="xs:Name" use="required"/>
			<xs:attribute name="invert" type="xs:boolean" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="state">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="s:event" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:Name" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="target">
		<xs:complexType>
			<xs:attribute name="state" type="xs:Name" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="work-flow">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="s:state" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:Name" use="required"/>
			<xs:attribute name="error-state" type="xs:Name" use="required"/>
			<xs:attribute name="initial-state" type="xs:Name" use="required"/>
		</xs:complexType>
		<xs:key name="state-name">
			<xs:selector xpath=".//s:state"/>
			<xs:field xpath="@name"/>
		</xs:key>
		<xs:keyref name="initial-state-ref" refer="s:state-name">
			<xs:selector xpath="."/>
			<xs:field xpath="@initial-state"/>
		</xs:keyref>
		<xs:keyref name="error-state-ref" refer="s:state-name">
			<xs:selector xpath="."/>
			<xs:field xpath="@error-state"/>
		</xs:keyref>
		<xs:keyref name="state-ref" refer="s:state-name">
			<xs:selector xpath=".//s:target"/>
			<xs:field xpath="@state"/>
		</xs:keyref>
	</xs:element>
	<xs:element name="work-flows">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="s:work-flow" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="model" use="required" type="xs:anyURI"/>
		</xs:complexType> 
		<xs:key name="workflow-names">
			<xs:selector xpath=".//s:work-flow"/>
			<xs:field xpath="@name"/>
		</xs:key>
		<xs:key name="state-names">
			<xs:selector xpath=".//s:state"/>
			<xs:field xpath="@name"/>
		</xs:key>
		<xs:keyref name="guard-state" refer="s:state-names">
			<xs:selector xpath=".//s:guard"/>
			<xs:field xpath="@state"/>
		</xs:keyref>
	</xs:element>
</xs:schema>

=== koenh1/pigml/data/entity-schemas/message-workflow.xml
<work-flows xmlns="http://www.wolterskluwer.com/schemas/appollo/entity/v1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.wolterskluwer.com/schemas/appollo/entity/v1.1 file:///C:/wkb/git/pigml/schemas/wkbe-workflows-schema.xsd"
model="message-model.xml">
	<directory href="/messages/" depth="1"/>
	<directory href="/entities/" depth="Infinity"/>
	<import-module prefix="ex" namespace="http://www.wolterskluwer.com/ns/appollo/marklogic/entity/example" href="/lib/example.xqy"/>
	<work-flow name="sent-state" initial-state="unsent">
		<state name="unsent">
			<event action="send" async="true" retryable="true">
				<guard state="ready"/>
				<target state="sent"/>
			</event>
		</state>
		<state name="sent"/>
	</work-flow>
	<work-flow name="message-state" initial-state="incomplete">
		<state name="incomplete">
			<event action="add-receiver" argument-type="element(address)">
				<guard invert="true" state="sent"/>
				<target state="ready"/>
				<target state="incomplete"/>
			</event>
			<event action="set-subject" argument-type="string">
				<guard invert="true" state="sent"/>
				<target state="ready"/>
				<target state="incomplete"/>
			</event>
			<event action="add-message" argument-type="element(message)">
				<guard invert="true" state="sent"/>
				<target state="ready"/>
				<target state="incomplete"/>
			</event>
			<event action="add-attachment" argument-type="base64Binary">
				<guard invert="true" state="sent"/>
				<target state="ready"/>
				<target state="incomplete"/>
			</event>
		</state>
		<state name="ready">
			<event action="add-receiver" argument-type="element(address)">
				<guard invert="true" state="sent"/>
				<target state="ready"/>
			</event>
			<event action="set-subject" argument-type="string">
				<guard invert="true" state="sent"/>
				<target state="ready"/>
			</event>
			<event action="add-message" argument-type="element(message)">
				<guard invert="true" state="sent"/>
				<target state="ready"/>
			</event>
		</state>
		<state name="final">
				</state>
	</work-flow>
</work-flows>

=== koenh1/pigml/data/entity-schemas/example2.xml
<work-flows xmlns="http://www.wolterskluwer.com/schemas/appollo/entity/v1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.wolterskluwer.com/schemas/appollo/entity/v1.1 file:///C:/wkb/git/pigml/schemas/wkbe-workflows-schema.xsd">
	<work-flow name="sent-state" initial-state="unsent" error-state="unsent">
		<state name="unsent">
			<event action="send">
				<guard state="ready"/>
				<target state="sent"/>
			</event>
		</state>
		<state name="sent"/>
	</work-flow>
	<work-flow name="message-state" initial-state="incomplete" error-state="incomplete">
		<state name="incomplete">
			<event action="add-receiver" argument-type="element(receiver)">
				<guard invert="true" state="sent"/>
				<target state="ready"/>
				<target state="incomplete"/>
			</event>
			<event action="set-subject" argument-type="string">
				<guard invert="true" state="sent"/>
				<target state="ready"/>
				<target state="incomplete"/>
			</event>
			<event action="add-message">
				<guard invert="true" state="sent"/>
				<target state="ready"/>
				<target state="incomplete"/>
			</event>
		</state>
		<state name="ready">
			<event action="add-receiver">
				<guard invert="true" state="sent"/>
				<target state="ready"/>
			</event>
			<event action="set-subject">
				<guard invert="true" state="sent"/>
				<target state="ready"/>
			</event>
			<event action="add-message">
				<guard invert="true" state="sent"/>
				<target state="ready"/>
			</event>
		</state>
		<state name="final">
				</state>
	</work-flow>
</work-flows>
